### ISSUE TITLE
interactively selecting species name for site management locations

### ISSUE THREAD

**Issue by daisyduursma** [daisyduursma/OEHDecisionFramework#2]
In the file app.R, I interactively select the location of, and upload a .shp file of polygons that are currently protected for the SOS species. This appears to be working. This shape file has polygons for 400 species. I would like to interactively select the species I am interested in.

The code I have written does seem to generate the species list to (siteSP). 

```#SOSspecies
  SOSsites <- eventReactive(input$SOSsitefile, {
    req(input$SOSsitefile)
    # read in SOS site managment shapefile  
    sites <- tools::file_ext(input$uploadedfile)[1]#get extension
    if(fext == "shp"){
      sos <- shapefile(input$SOSsitefile$datapath,
                        p4s = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
      return(sos)
    } 
    #make list of species names
    siteSP <- unique(sites@data$SciName)#vector of species names
    # Identify species interested in
    updateSelectInput(session, "SOSspecies", "Select management site species name:",
                      choices = siteSP, selected="")
  })
```

**Comment by RemkoDuursma** [comment]
The code given has some bugs, but after fixing those, the real problem here is having Shiny read the shapefile. Since the shapefile is not a single `.shp` file, but a bunch of other ones as well (`.shx` etc.), it is quite difficult to get this to work!

Similar problem: https://groups.google.com/forum/#!topic/shiny-discuss/FtI76rdvoHI

Options are 1) upload zipped shapefile (annoying for user), 2) force user to select all shapefile-related files (using Shift, also annoying!), 3) pre-read shape files and save as rds, and upload those. If there are only so many shapefiles, this could be a nice solution (but needs a little data management on the OEH side)

**Comment by RemkoDuursma** [comment]
Bugs mentioned are:

`sites <- tools::file_ext(input$uploadedfile)[1]#get extension`

should be `fext <-`, the file extension (used in the line below).

Second, this `eventReactive` is not actually used in the example code. You have to add something like,

```
  observeEvent(input$SOSsitefile, {
    
    soss <- SOSsites()
    updateSelectInput(session, "SOSspecies", "Select management site species name:",
                      choices = soss, selected="")
  })
```

just like you did previously for species codes.
(
